version: '3.7'

services:
  e_dev:
    container_name: jshd302_express_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  e_prod:
    container_name: jshd302_express_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  e_test:
    container_name: jshd302_express_test
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
